version: "3.9"
services:
  hotel-api:
    image: hotel-api
    container_name: hotel-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: roberth456
      MYSQL_DATABASE: alura
      MYSQL_USER: hack4you
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume: